language: php
git:
  depth: 1
cache:
  directories:
  - "$HOME/.composer/cache"
sudo: false
env:
  global:
  - COMPOSER_ALLOW_XDEBUG=0
matrix:
  include:
    - php: 7.1
      env: CONTAO_VERSION='4.4.*'
    - php: 7.2
      env: CONTAO_VERSION='4.4.*'
    - php: 7.1
      env: CONTAO_VERSION='4.5.*'
    - php: 7.2
      env: CONTAO_VERSION='4.5.*'
    - php: 7.2
      env: COVERAGE=1 CONTAO_VERSION='4.5.*'
  allow_failures:
    - env: COVERAGE=1 DEFAULT=0
  fast_finish: true
before_install:
- if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || true; fi
install:
- if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --no-interaction --quiet; fi
- composer update $COMPOSER_FLAGS --no-interaction --no-suggest
notifications:
  email:
    recipients:
    - digitales@heimrich-hannot.de
    on_success: never
    on_failure: always
  hipchat:
    rooms:
      secure: tXs/gq0FZIKLkbMtdsNyUpjbWVKWru140F4DExJF5w+L1pNuPUSvGtADOrxez2bznY15Gffbx/4YhYkAkb1MVeibNkDa19dXiysDwds5lr2lPsQY1NNd4tb1crZi1rsx4lArIgz/b4GxaFtUOX+VFCHsV6XyXzwo2iiO8JWqIwW4Uvb+HReZ50UrTnuczwfKosXwrRNxdQXVZDXy3QDRyUJDB0hyb8Q4b5cm8UH8FEpmc5coAx6HTLiMTHYgHsl3YW8umUxpQuIgaGLl90w27KURDSTbBpMoaSbhzyNpFfOSMIMjla5n8IV9R+PS9T938BTJGAg/916o+onq1+YCO0n6rwcG/JYOzKpdu8Wbgx63rGAxtplwYQ6zwlfQwVWBTYRQD1yBmSqEhOvpk+CyR+GF+t2HjvwTFgISxpkkEuewgFTav6ON+j3ZezbndjwvJJMx/jb4j2oKq04LqrXVvNkSv5Xgo3hzItz/s0NxvPHE+9irzRt7gFkM3TjeAuQYAK+V6u6M1z2mFqOt1N+7lZRk89uhYYVZJsEaHjWdoiKPrKbJGVMcgDQQGK699NJEm+DXBfPTADnhZE4O2+SSVpXW1rnpmfmIY9J9vTbSTwmlj8HoDf7NZ0KdulBAuvLkrVNQA1gHiIrp2roPegyOnzpNMbXz1SHYcWlGz71IFGU=
before_script:
- travis_wait composer install --no-interaction
script:
- if [[ "$COVERAGE" = "1" ]]; then travis_retry mkdir -p build/logs; fi
- if [[ "$COVERAGE" = "1" ]]; then travis_retry php vendor/bin/phpunit --coverage-clover build/logs/clover.xml || true; fi
after_script:
- if [[ "$COVERAGE" = "1" ]]; then travis_retry php vendor/bin/php-coveralls -v; fi