services:
    hh.contao-newsalert.listener.newspostedlistener:
        class: HeimrichHannot\ContaoNewsAlertBundle\EventListener\NewsPostedListener
        arguments:
            - '@service_container'

    hh.contao-newsalert.listener.dcaListener:
        class: HeimrichHannot\ContaoNewsAlertBundle\EventListener\DataContainer\NewsalertListener
        arguments:
            - '@service_container'

    hh.contao-newsalert.newstopiccollection:
        class: HeimrichHannot\ContaoNewsAlertBundle\Components\NewsTopicCollection
