services:
  huh.newsalert.listener.newsposted:
    class: HeimrichHannot\ContaoNewsAlertBundle\EventListener\NewsPostedListener
    public: true
    arguments: ['@service_container']

  huh.newsalert.listener.callback.table.modules:
    class: HeimrichHannot\ContaoNewsAlertBundle\EventListener\ModulesTableCallbackListener
    arguments: ['@contao.framework']

  huh.newsalert.topiccollection:
    public: true
    class: HeimrichHannot\ContaoNewsAlertBundle\Components\NewsTopicCollection

  HeimrichHannot\ContaoNewsAlertBundle\Components\NewsArchiveTopics:
    tags: [hh.newsalert.topic_source]

# Deprecated aliases

  hh.contao-newsalert.listener.newspostedlistener:
    alias: huh.newsalert.listener.newsposted
    deprecated: The service has beed renamed to huh.newsalert.listener.newsposted and this alias will soon be deleted.

  hh.contao-newsalert.newstopiccollection:
    alias: huh.newsalert.topiccollection
    deprecated: The service has beed renamed to huh.newsalert.newstopiccollection and this alias will soon be deleted.