services:
    hh.contao-newsalert.listener.newspostedlistener:
        class: HeimrichHannot\ContaoNewsAlertBundle\EventListener\NewsPostedListener
        arguments:
            - '@service_container'

    hh.contao-newsalert.newstopiccollection:
        class: HeimrichHannot\ContaoNewsAlertBundle\Components\NewsTopicCollection

    HeimrichHannot\ContaoNewsAlertBundle\Components\NewsArchiveTopics:
        tags: [hh.newsalert.topic_source]
